---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson
  name: handson
spec:
  type: ClusterIP
  ports:
  - name: http-app
    port: 9999
    protocol: TCP
    targetPort: httphoge
  selector:
    app: handson
